export class ConstructPaymentObject{



  returnPaymentObject=function (paymentDetails) {

    var paymentObject= {
      "AccountAdjusmentSD":[
        {
            "AccStatusCode":"AC",
            "ActivitySource":"Internal",
            "ActivityType":"PLANFEE",
            "AdjustmentCategory":"PostPaid",
            "AdjustmentCategoryId":"0",
            "AdjustmentDate":"\/Date(1245398693390)\/",
            "AdjustmentLevelId":"0",
          "AdjustmentLineItems":[
            {
              "AdjustmentId":"0",
              "Amount":20,
              "AppTxnTypeCode":"CSCPLANFEEPOST",
              "FeeCode":"EXPFEE",
              "LinkId":"0",
              "LinkSourceName":"null",
              "PlanID":"4",
              "UserName":"null"
            },
            {
              "AdjustmentId":"0",
              "Amount":"50",
              "AppTxnTypeCode":"CSCPLANFEEPOST",
              "FeeCode":"ENROLLFEE",
              "LinkId":"0",
              "LinkSourceName":"null",
              "PlanID":"4",
              "UserName":"null",
              "Raw View":"",
              "AdjustmentReason":"null",
              "AmountType":"null",
              "ApprovedStatusDate":"\/Date(1245398693390)\/",
              "BusinessProcessCode":"null",
              "CCPaymentTxnId":"0",
              "CCVoucherNo":"null",
              "CSVRewardIds":"null",
              "CustomerId":"10257631",
              "CustomerTripId":"0",
              "CustTripIdCSV":"null",
              "Description":"Received Plan Fee by Adjustment for Postpaid Customers",
              "DrCr_Flag":"D",
              "endDate":"\/Date(1245398693390)\/",
              "EndDate":"\/Date(1245398693390)\/",
              "ICNId":"40026",
              "IsAnonymousTransfer":"FALSE",
              "IsApproved":"Approved",
              "IsApprovedUser":"FALSE",
              "IsChangeOfPlan":"FALSE",
              "IsManualEntry":"FALSE",
              "IsPostpaidCustomer":"TRUE",
              "IsSingleTransaction":"FALSE",
              "IsTransferredPostpaidCustomer":"FALSE",
              "ISTripLvel":"FALSE",
              "IsTripTransfer":"FALSE",
              "IsVehicleTransfered":"FALSE",
              "NSFCheckNumber":"null",
              "OtherPlanFee":"0",
              "PreviousBalance":"-124",
              "ReasonCode":"null",
              "RedeemRewardPoints":"0",
              "ReferralCustomerId":"0",
              "RefPkId":"0",
              "RevenueCategory":"null",
              "RewardBalances":"0",
              "RewardPoint":"0",
              "StartDate":"\/Date(1245398693390)\/",
              "startDate":"\/Date(1245398693390)\/",
              "Stmt_Literal":"null",
              "strSubSystem":"null",
              "SubSystem":"CSC"
            }
          ]
        },
        {
          "SystemActivity":[
            {
              "TollAmount":"0",
              "TotalAmount":"70",
              "TransactionDateTime":"\/Date(1245398693390)\/",
              "TransferCustomerId":"0",
              "TripId":"0",
              "TripOutStandingAmount":"0",
              "TripProblemId":"0",
              "TripStageId":"0",
              "TripStatusId":"0",
              "TripTransfer":"FALSE",
              "TxnAmount":"10",
              "TxnCategory":"FEE",
              "TxnType":"Adjustment",
              "TxnTypeDesc":"null",
              "User":"tpsuperuser",
              "VehicleId":"0",
              "VehicleNumber":"null",
              "VocherNumber":"null",
              "AccountIntegration":"CreateAccount",
              "AccountStatus":"NA",
              "ActivitySource":"Internal",
              "ActivityType":"PMTCREDITCARD",
              "BankPayments":"null",
              "CardMode":"null",
              "CashPayments":"null",
              "ChequePayments":"null"
            }
          ]
        },
        {
          "CreditCardPayments":[
            {
              "CardMode":"null",
              "CCID":"0",
              "CCSuffix4":"1111",
              "City":"uuuuuuuuuuuu",
              "Country":"IND",
              "CreditCardNumber":"DpPovBxMt5LcYcLkMmsVatSQqhrFdF8hFx3fX3sUd2s=",
              "CreditCardType":"VISA",
              "CVV":"",
              "DefaultFlag":"FALSE",
              "ExpiryDate":"202510",
              "ExpiryMonth":"10",
              "ExpiryYear":"2025",
              "Gateway":"PayPal",
              "Line1":"sfsdfsdfdf",
              "Line2":"",
              "Line3":"",
              "NameOnCard":"tesdrwr",
              "NewAddress":"FALSE",
              "State":"MP",
              "Zip1":"333333",
              "Zip2":"",
              "CreditCardServiceTax":"1.24",
              "CustomerBalance":"0",
              "CustomerId":"10257631"
            },
            {
              "CustomerTransaction":[
                {

                },
                {
                  "CustomerTransactions":[
                    {
                      "Description":"Create Account Payment",
                      "EMIINVPath":"null",
                      "ErrorMsg":"null",
                      "GiftCertificates":"null",
                      "ICNId":"40026",
                      "IntiatedBy":"tpsuperuser",
                      "InvoiceAmount":"0",
                      "InvoiceCSV":"null",
                      "InvoiceCycle":"null",
                      "InvoiceDay":"1",
                      "InvoiceID":"0",
                      "InvoiceIntervalId":"4",
                      "InvoiceListPath":"null",
                      "InvoiceNo":"null",
                      "InvoiceNoToReturn":"null",
                      "IsAddNewBankDetails":"FALSE",
                      "IsAddNewCardDetails":"FALSE",
                      "IsCreateAccountSystemUserActivity":"TRUE",
                      "IsNewAddress":"TRUE",
                      "IsNewCard":"FALSE",
                      "IsPostpaidCustomer":"TRUE",
                      "IsSplitCustomer":"FALSE",
                      "LinkSourceName":"PAYMENTS",
                      "LoggedUserId":"10257631",
                      "LoginId":"0",
                      "LstBankPayments":"null",
                      "LstChequePayments":"null",
                      "LstCreditCardPayments":"null",
                      "lstGiftCertificates":"null",
                      "MoneyOrderPayment":"null",
                      "NSFAmount":"0",
                      "ObjAdvancedPayment":"null",
                      "ObjAnonymousPayments":"null",
                      "objEMIRequest":"null",
                      "objListInvoices":"null",
                      "objListTrips":"null",
                      "OtherPlanFee":"70",
                      "ParentPaymentId":"0",
                      "ParentPaymentMode":"AllTransaction",
                      "PartialPaymentReason":"null",
                      "PaymentDate":"\/Date(1245398693390)\/",
                      "PaymentFor":"null",
                      "PaymentGateways":"PayPal",
                      "PaymentId":"0",
                      "PaymentMode":"CreditCard",
                      "PaymentModeDesc":"null",
                      "PaymentStatus":"InProcess"
                    }
                  ]
                },
                {
                  "PaymentTxnLineItem":[
                    {
                      "Description":"CSCPOSTCCPMT",
                      "LinkSourceName":"Tp_customerTrips",
                      "TxnAmount":"124",
                      "Raw View":"",
                      "PlanID":"4",
                      "PromoCode":"null",
                      "PromoId":"0",
                      "PromoPayments":"null",
                      "RefundType":"null",
                      "ReplenishmentType":"CreditCard",
                      "RetailerId":"0",
                      "RetailerLstTransactions":"null",
                      "Static members":"null",
                      "RetailerTransaction":"null",
                      "RevenueCategory":"Revenue",
                      "RRID":"0"
                    }
                  ]
                },
                {
                  "ShipmentAddress":[
                    {
                      "_fullAddress":"null",
                      "ActivitySource":"Internal",
                      "AddressId":"0",
                      "CheckBlockList":"FALSE",
                      "City":"dfgdgdgdfg",
                      "Country":"IND",
                      "CountryName":"null",
                      "CustomerId":"10257631",
                      "FullAddress":"fgdgdgf, dfgdgdgdfg, KL, 444444, IND",
                      "IsActive":"TRUE",
                      "IsActivityRequired":"TRUE",
                      "IsInvalidAddress":",FALSE",
                      "IsPreferred":"TRUE",
                      "IsShipmentupdateAddress":"FALSE",
                      "Line1":"fgdgdgf",
                      "Line2":"",
                      "Line3":"",
                      "LoginId":",0",
                      "Paging":"null",
                      "ReasonCode":"null",
                      "State":"KL",
                      "StateName":"null",
                      "SubSystem":"CSC",
                      "Type":"Shipping",
                      "UserId":"0",
                      "UserName":"tpsuperuser",
                      "Zip1":"444444",
                      "Zip2":"",
                      "Raw View":"",
                      "SplitParentCustomerId":"0",
                      "StatementCycle":""
                    }
                  ]
                },
                {
                  "SystemActivity":[
                    {
                      "ActionCode":"null",
                      "ActivitySource":"null",
                      "ActivityTypeDescription":"null",
                      "CustomerId":"0",
                      "FeaturesCode":"null",
                      "IsSearch":"FALSE",
                      "IsViewed":"FALSE",
                      "KeyValue":"null",
                      "LoginId":"611296",
                      "SubSystem":"null",
                      "User":"tpsuperuser",
                      "UserId":"10000001",
                      "TagDeliveryOption":"ShipmentByPost"
                    }
                  ]
                },
                {
                  "TagRequests":[
                    {
                      "ActivitySource":"Internal",
                      "ActivityType":"Login",
                      "AdjustmentReason":"null",
                      "AssignedOrReturnedType":"null",
                      "CustomerId":"10257631",
                      "CustTagReqId":"0",
                      "EndEffectiveDate":"\/Date(1245398693390)\/",
                      "FacilityCode":"null",
                      "FulfilledQty":"0",
                      "HexTagNumber":"null",
                      "ICNId":"0",
                      "IsNotification":"FALSE",
                      "IsPageLoad":"FALSE",
                      "IsReplacedTagReturned":"FALSE",
                      "IsSearch":"FALSE",
                      "ItemCode":"null",
                      "LoginId":"0",
                      "ManufactureDate":"\/Date(1245398693390)\/",
                      "Mounting":"INTERNAL",
                      "PreviousDate":"null",
                      "PreviousTagAlias":"null",
                      "PreviousTagStatus":"null",
                      "Protocol":"6C",
                      "PurchaseOrderNumber":"null",
                      "ReqCount":"1",
                      "RMANumber":"null",
                      "SerialNumber":"null",
                      "ShipmentAddress":"null",
                      "ShipmentId":"0",
                      "SplitCustomerId":"0",
                      "StartEffectiveDate":"\/Date(1245398693390)\/",
                      "StatusDate":"\/Date(1245398693390)\/",
                      "SubSystem":"CSC",
                      "TagAlias":"null",
                      "TagDeliveryMethod":"0",
                      "TagDeliveryOption":"null",
                      "TagLocation":"null",
                      "TagName":"No. Of 6C_INTERNAL(s):",
                      "TagPurchaseMethod":"0",
                      "TagPurchaseMethodCode":"ShipmentByPost",
                      "TagReqComment":"null",
                      "TagReqDate":"{9/12/2017 6:43:09 PM}",
                      "TagReqType":"New",
                      "TagSearchActivityInd":"FALSE",
                      "TagStatus":"null",
                      "TagTobeReplaced":"null",
                      "TagType":"null",
                      "TotalRequiredAmount":"0",
                      "UserId":"0",
                      "UserName":"tpsuperuser",
                      "VehicleClassId":"null",
                      "VehicleId":"0",
                      "WarrantyEndDate":"\/Date(1245398693390)\/",
                      "Raw View":"",
                      "TotalAmount":"0",
                      "TotalShippingFee":"0",
                      "TransferredAmt":"0",
                      "TripIds":"null",
                      "TripListPath":"null",
                      "TxnAmount":"125.24",
                      "TxnCategory":"PAYMENT",
                      "UserType":"NonCustomer",
                      "VEPVehicles":"null",
                      "VoucherNumber":"null"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }


    return paymentObject;

      }
}
